### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by AlbertFR**
Hi,

Please can you update translations ?

### CODE REVIEW

**Comment by AlbertFR** [comment]
any news ?

**Comment by aerkalov** [comment]
News about what exactly? Although it is not marked here in GitHub this PR has been merged together with #254 PR with translations.

**Comment by danielhjames** [comment]
Hi Aco, there are also new French strings for 2.0 that Albert has been working on in https://github.com/sourcefabric/Booktype/pull/233

I would suggest merging #233 and closing #253 to clean this up.

**Comment by aerkalov** [comment]
#253 has been merged into branch "dev" because it is for Booktype 1.6. Closing this now.

**Pull request closed without merging**
