### PR TITLE
BK-1870 Add Japanese and Czech to language selector, update book language list

### PR DESCRIPTION
**Pull request by danielhjames**
Book language list had got a little behind the interface language list.

### CODE REVIEW

**Comment by danielhjames** [comment]
Adding Czech means we are now in sync with Transifex languages that are more than 0% complete.

**Comment by aerkalov** [comment]
The important thing to know here is that this new list of languages will only work on newly created instanced. Django data migration must be used to make it work on newly created and existing instances with the same change.

**Comment by danielhjames** [comment]
Will they be available on booktype-dev.sourcefabric.org please? It helps the translators to see their work in context.

**Comment by aerkalov** [comment]
No. They have to be manually updated each time. That includes the setting file (for the list of translations) and fixture file (for the list book languages). I have done 1st thing on the dev so translators will be able to see it.

**Comment by danielhjames** [comment]
Thanks! I will inform the translators.

**Pull request merged**
