### PR TITLE
BK-2040 Adds support for Django 1.9

### PR DESCRIPTION
**Pull request by eos87**
hi @olegpshenichniy, please have a look of this when you have some time. You can check BK-2040 for some additional details in comments :) Thanks!

p.s. This should work with 1.8 < and < 1.10

### CODE REVIEW

**Comment by MiczFlor** [comment]
Shouldn't we make this a new minor version? Just to have a clear distinction between the two Django versions?

**Comment by eos87** [comment]
We decided some time ago we're no doing minor releases, so I was thinking more like releasing 2.2 together with api and new book reader :) We should discuss this with the rest of the team though.

**Comment by olegpshenichniy** [comment]
Hello @eos87,
PR Looks good and it works for me.
The only thing I would like to change is to get rid of old CONSTANTS in `skeleton/*_settings.py.original` files:

`TEMPLATE_LOADERS, TEMPLATE_CONTEXT_PROCESSORS, TEMPLATE_DIRS` - I would like to remove them forever and put everything into one TEMPLATES constant. It will simplify settings, but it will make update process of already existing instances a little bit longer, but I think it makes sense.
The same with 
```
TEMPLATE_DEBUG -->> TEMPLATES = [
    {
        # bla bla
        'OPTIONS': {
            'debug': DEBUG or True/False,
        },
    },
]
```

In general we will have all templates related settings in one const, something like:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BOOKTYPE_ROOT.child(BOOKTYPE_SITE_DIR).child('templates')
        ],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.eggs.Loader',
                'booktype.apps.themes.loaders.Loader'
            ],
            'debug': True
        },
    },
]
```

and on the instance level we can:
```
TEMPLATES[0]['DIRS'] += [
    os.path.join(BOOKTYPE_ROOT, 'lib/<instance>/convert/<custom_converter>/templates'),
]
```

Let me know if it makes sense.

**Comment by eos87** [comment]
Hi @olegpshenichniy, I updated the PR. Please take a look and merge it. Will send the one for API once this is merged, because api one depends on this.

**Pull request merged**
