### PR TITLE
BK-1982 UX - Multi-user bug with theme selection

### PR DESCRIPTION
**Pull request by olegpshenichniy**
Hi @eos87 , please check this pr when you have a time. 

What is done:
- changed relation between user/book/theme. Now book can have only one theme selected.
- created schema and data migrations.
- improved UI/UX.

**Before checking it, don't forget to backup your DB 🏬**
For testing it, try to attach 2 or more users to the book, open editor for each user and select different themes for all of them. For better testing, do it with 2 or more books simultaneously. After preparations are done --->> run the migrations 👾

### CODE REVIEW

**Comment by eos87** [comment]
Hi @olegpshenichniy, please just change the model name to `BookTheme` as we talked the other day ;)

**Comment by olegpshenichniy** [comment]
Hi @eos87 , Model name was changed as we discussed.

**Comment by eos87** [comment]
I'll complete testing this tomorrow.

**Comment by olegpshenichniy** [comment]
Hi @eos87 ,
Please, check this pr. It's blocker one.

**Pull request merged**
