### PR TITLE
BK-830 Hostnames which can access book dump must be configurable

### PR DESCRIPTION
**Pull request by byroncorrales**
Code was mostly adapted from django core https://github.com/django/django/blob/master/django/http/request.py#L92

### CODE REVIEW

**Comment by aerkalov** [comment]
Unfortunately for you, it is not that simple :) We can not just like that copy Django code (under Django license) into Booktype (under AGPL). I am not sure if they (licenses) are compatible for that, plus even if we do that we would need to include Django copyright notice with Booktype. We also have dual licensing for Booktype (for commercial things). I am not really sure we could do it with this copy+pasted code. The code we are talking about is way to small to include all this license hassle in this task.

You have two options left. Write this minimal part yourself using fnmatch module. This way we would be able to include IP ranges or something like that, for instance 192.168.* in our allow list. The other method would be to use these functions from already installed Django. I am not sure if this is public or private API  and if it would change (i can see it has changed from 1.5=>1.6), so you will have to check it.

**Comment by byroncorrales** [comment]
I was not aware about that, oops! , I will fix it and push it again

**Comment by byroncorrales** [comment]
@aerkalov  could you please check again, I have updated the PR

**Comment by eos87** [comment]
It looks good, just fixed couple of lines not PEP8 compliant. Merged.

**Pull request closed without merging**
