### PR TITLE
BK-1361 Add some more tooltips and remove a duplicate string

### PR DESCRIPTION
**Pull request by danielhjames**
Currently we have both 'Create new group' and 'Create New Group' but on a button the string is transformed to uppercase anyway.

### CODE REVIEW

**Comment by danielhjames** [comment]
When I regenerate the .po file with:

django-admin.py makemessages -l en

it creates a large diff, I'm not sure why. Please advise if you use a different command, or it may be a line endings issue.

**Comment by aerkalov** [comment]
First, you should squash your commits into just one before sending PR :)

Makemessages checks your current location when it creates .po files. So the diff might have something to do with that. For instance:

```
-#: apps/account/templates/account/dashboard_create_book_modal.html:47
+#: booktype/apps/account/templates/account/dashboard_create_book_modal.html:47
 msgid "Book Image"
```

It records location where that string was mentioned. In the first case I ran the command from Booktype/lib/booktype/ while in the second case from Booktype/lib/ directory. This might be the reason why your diff is too big. Every path has been changed so it must change it.

**Comment by danielhjames** [comment]
Hi Aco, I'm happy to squash commits, every Sourcefabric project is a little different :-)

As for the .po file diffs, the issue is not the path, it has to do with the word wrap of comments, similar to https://github.com/mbi/django-rosetta/issues/24 Probably it is a cross-platform issue. If you don't mind the diff being larger than it should be, I can generate the .po each time.

**Comment by danielhjames** [comment]
All in one commit with regenerated .po file now.

**Pull request merged**
