### PR TITLE
BK-1438 font-plugin.js for Aloha editor does not work properly

### PR DESCRIPTION
**Pull request by eos87**

### CODE REVIEW

**Comment by eos87** [comment]
@aerkalov check again

**Comment by eos87** [comment]
Hey @aerkalov I've made some fixes here. Can you check it again please?

**Comment by aerkalov** [comment]
@eos87 I did not test it a lot but I noticed couple of times.

Original text
```html
<h1>Der Herr der Ringe</h1>
<p>Ovo je neki moj tekst koji imam <b>s boladnim necim</b> i josh neshto iza.</p>
<p>Pa nakont oga ima josh neshto.</p>
```

Start select at *necim*, ends at *oga*.

```html
<h1>Der Herr der Ringe</h1>
<p>Ovo je neki moj tekst koji imam <b>s boladnim <span style="font-family:sans-serif">necim</span></b><span style="font-family:sans-serif"> i josh neshto iza.</span></p><span style="font-family: sans-serif;">
</span><p><span style="font-family:sans-serif">Pa nakont oga</span> ima josh neshto.</p>
```

2nd test. This is original text.
```html
<h1>Der Herr der Ringe</h1>
<p>Ovo je neki moj tekst koji imam <b>s boladnim necim</b> i josh neshto iza.</p>
<p><span style="font-family: serif;">Pa nakont oga ima josh neshto.</span></p>
```

Same selection like before and this is the result:
```html
<h1>Der Herr der Ringe</h1>
<p>Ovo je neki moj tekst koji imam <b>s boladnim <span style="font-family:sans-serif">necim</span></b><span style="font-family:sans-serif"> i josh neshto iza.</span></p><span style="font-family: sans-serif;">
</span><p><span style="font-family: serif;">Pa nakont oga ima josh neshto.</span></p>
```

3rd thing I tested was in a table. When you double click on the cell it selects it. Change font for that selection. It will add <span> tag around <div> editable tag. This is not valid at the end because <span> will not be visible in end HTML (visible in Edit Raw HTML option in the menu). In editor it looks ok but output format (visible with Edit Raw HTML) is not valid. Also noticed double clicking and selecting font does not work all of the times. Selecing part of the text works.

**Comment by eos87** [comment]
Hey @aerkalov, i did some improvements in order to fix the wrong behavior that you told me and some other that I noticed. Regarding the tables (and heading tags), there one more problem there and it seems to be related with the editor. It makes those tags `editable` so we need to figure out that before finalizing the font-plugin one. Let's talk more about this tomorrow.

**Comment by eos87** [comment]
Hey @aerkalov, I did the needed fixes for the Aloha content-editable tags (headings and tables). Can you please check this again? 
Thanks!

**Comment by aerkalov** [comment]
I did some testing with it. I noticed couple of things.

Sometimes it likes to put two `<span>` elements around something. The other thing is that it likes to put `<span>` element around all `<li>` elements, which shouldn't happen.

Here is one example which shows both of the things. Selection started with word "je prije" and ended at the end of the document.

*Before*
```
<h1>dsfdf</h1>
<p>Ovo je prije</p>
<ol>
  <li>jedan</li>
  <li>dva</li>
  <li>tri</li>
</ol>
<p>Ovo je iza</p>
```

*After*
```
<h1>dsfdf</h1>
<p>Ovo <span style="font-family: sans-serif">je prije</span></p>
<ol>
  <span style="font-family: sans-serif;">
    <li><span style="font-family: sans-serif;">jedan</span></li>
    <li><span style="font-family: sans-serif;">dva</span></li>
    <li><span style="font-family: sans-serif;">tri</span></li>
  </span>
</ol>
<p><span style="font-family: sans-serif;"><span style="font-family: sans-serif;">Ovo je iza</span></span></p>
```

**Comment by aerkalov** [comment]
Merged

**Pull request closed without merging**
