### PR TITLE
BK-2200 Add suffix for icml/docx output file name

### PR DESCRIPTION
**Pull request by olegpshenichniy**
This PR also contains BK-2197.

### CODE REVIEW

**Comment by eos87** [comment]
The `sh` don't look so great I would say. Let's improve them later as we talked

**Comment by olegpshenichniy** [comment]
@eos87 yes, this is what I thought in the very beginning. In general, we will remove shell script layer asap, and we'll use just python as it should be.

**Comment by MiczFlor** [comment]
Yes, sure. Let's make it work first. There is nothing wrong with good old rusty shell scripts. The are the diesel engines that keep the web running.

**Comment by eos87** [comment]
> There is nothing wrong with good old rusty shell scripts

hahaha I read this hearing your voice. I agree there is nothing wrong, they work fine and for sure we can always improve as we move on :)

**Pull request merged**
