### PR TITLE
Finnish localization

### PR DESCRIPTION
**Pull request by TomiToivio**
Updated Finnish .po files.

### CODE REVIEW

**Comment by danielhjames** [comment]
This might be better in the devel branch for 1.6 updates.

**Comment by danielhjames** [comment]
Hi Tomi, I have put these strings into our project at https://www.transifex.com/sourcefabric/booktype/language/fi/ so they will be automatically merged to GitHub in future. This means you will no longer need to make pull requests to update Finnish strings.

**Comment by danielhjames** [comment]
This pull request should be closed as it won't merge cleanly into master now, the Finnish strings now come from the Transifex version.

**Comment by eos87** [comment]
Closing this. We're handling strings translation in Transifex. Any help translating is more than welcome :) https://www.transifex.com/sourcefabric/booktype/

**Pull request closed without merging**
